version: '2'
services:

  oracle:
    image: oracle/database:12.2.0.1-se2
    container_name: oracle
    hostname: oracle
    ports:
      - 1521:1521
      - 5500:5500
    environment:
       ORACLE_SID: "RHTestDB"
       ORACLE_PWD: "D4V!t4T3st"
    shm_size: 8g
    volumes: 
      - /Users/rachelhughes/github/Davita/dwbi_temp_project/OracleDatabase/samples/customscripts:/opt/oracle/scripts/startup

  python:
    image: dva_python
    container_name: python
    hostname: python
    volumes:
      - /Users/rachelhughes/Git:/usr/local/src/mystuff
    links:
      - oracle
